name: Deploy CAP to SAP BTP


env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Dependencies
        run: npm install
        

      - name: Install CDS & MBT
        run: |
          npm install -g @sap/cds-dk
          npm install -g mbt

      - name: Build CAP Project
        run: cds build

      - name: Build MTA
        run: mbt build

      # 👉 THIS IS WHERE YOUR CODE STARTS
      - name: Clean old CF CLI
        run: |
              if [ -L /usr/local/bin/cf ]; then
              sudo unlink /usr/local/bin/cf
              fi

      - name: Setup CF CLI
        uses: cloudfoundry/cf-cli-action@v2

      - name: Install CF MultiApps Plugin
        run: |
          cf install-plugin -f multiapps

      - name: Login to SAP BTP
        run: |
          cf login -a ${{ secrets.CF_API }} \
                   -u ${{ secrets.CF_USERNAME }} \
                   -p ${{ secrets.CF_PASSWORD }} \
                   -o ${{ secrets.CF_ORG }} \
                   -s ${{ secrets.CF_SPACE }}

      - name: Deploy to BTP
        run: |
          cf deploy mta_archives/*.mtar